server:
  port: 8081

spring:
  application:
    name: scrapper
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092,localhost:29092,localhost:39092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
    admin:
      fail-fast: true



  datasource:
    url: jdbc:postgresql://localhost:5432/botdb
    username: botuser
    password: botpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
   enabled: false

app:
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    # access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
  client:
    base-url-for-bot: http://localhost:8080
  access-type: SQL
  messaging-type: kafka
  kafka:
    topic: link-updates
  monitor-service:
    batch-size: 1000
    launch-interval: 10000 # in ms
    threads: 4
